[project]
name = "video-streaming-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.2",
    "asyncpg>=0.30.0",
    "bcrypt==4.0.1",
    "fastapi>=0.115.12",
    "passlib==1.7.4",
    "psycopg>=3.2.9",
    "pydantic-settings>=2.8.1",
    "python-dotenv>=1.1.0",
    "python-jose>=3.5.0",
    "scalar-fastapi>=1.2.3",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.11",
]

[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4

target-version = "py312"

select = [
    "E", "F", "A", "BLE", "C4", "DTZ",
    "I", "S", "TRY", "UP", "W", "YTT"
]
ignore = ["S324"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

docstring-code-line-length = "dynamic"
